name: Pull Request Check
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      accessibility-branch: ${{ github.ref }}
  pr-ci-finished:
    name: PR CI Finished
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
